<?php
/* @var $this Ajde_Template_Parser_Phtml_Helper */
$this->requireJsLibrary('jquery', '1.4');

// Syntax Highlighting
$this->requireJsPublic('lib/syntaxhighlighter/shCore.js');
$this->requireJsPublic('shAutoloaderOnDOMReady.js');
$this->requireJsPublic('syntaxhighlighter.js');
$this->requireCssPublic('lib/syntaxhighlighter/shCore.css', Ajde_Document_Format_Html::RESOURCE_POSITION_FIRST);
$this->requireCssPublic('lib/syntaxhighlighter/shThemeDefault.css', Ajde_Document_Format_Html::RESOURCE_POSITION_FIRST); 

// HTML 5 Boilerplate
$this->requireCssFirst('reset');
?>
<!doctype html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<!--[if IE]><![endif]-->
		<title><?php echo Config::get('sitename'); ?></title>
		<meta name="description" content="">
		<meta name="author" content="">
		<base href="http://<?php echo Config::get('site_root'); ?>" />
		<?php echo Ajde::app()->getDocument()->getHead('css'); ?>
	</head>
	<!--[if lt IE 7 ]> <body class="ie6"> <![endif]-->
	<!--[if IE 7 ]>    <body class="ie7"> <![endif]-->
	<!--[if IE 8 ]>    <body class="ie8"> <![endif]-->
	<!--[if IE 9 ]>    <body class="ie9"> <![endif]-->
	<!--[if (gt IE 9)|!(IE)]><!--> <body> <!--<![endif]-->
		<div id='wrapper'>
			<img src='public/images/logo.png' width='137' height='75' alt='Ajde'/>
			<?php echo $this->includeModule('general/menu'); ?>
			<?php echo Ajde::app()->getDocument()->getBody(); ?>
			<?php echo $this->includeModule('general/footer'); ?>
		</div>
		<?php echo Ajde::app()->getDocument()->getScripts(); ?>
	</body>
</html>