<?php echo $this->ajaxForm('_core/component:crudCommit', $this->id, 'ACCrudEdit'); ?>
	
	<dl class='crudEdit'>
		<?php foreach($this->fields as $fieldName => $fieldLabel) { ?>
			<dt><?php echo !empty($fieldLabel) ? $fieldLabel : $fieldName; ?></dt>
			<?php
			if ($this->item->has($fieldName)) {
				$value = $this->item->get($fieldName);
			} else {
				$value = "";
			}
			// Linked Model
			if ($value instanceof AjdeX_Model) { ?>
				<dd><?php echo $value->get($value->getDisplayField()); ?></dd>
			<?php
			// Text value
			} else { ?>
				<dd>
					<input type="text" name="<?php echo $fieldName; ?>" value="<?php echo htmlentities($value); ?>" />
				</dd>
			<?php } ?>			
		<?php } ?>
		
		<dt>&nbsp;</dt>
		<dd>
			<input type="button" class="save" value="Save" />
			<a href="javascript:void(null);" class='cancel'>Cancel</a>
		</dd>
	</dl>
	
</form>