<?php echo $this->ajaxForm('component/crudCommit', $this->id, 'ACCrudList'); ?>

	<table class='crudList'>
	<thead>
		<tr>
			<th width="25"></th>
			<?php foreach($this->fields as $fieldName => $fieldLabel) { ?>
				<th><?php echo !empty($fieldLabel) ? $fieldLabel : $fieldName; ?></th>
			<?php } ?>
			<th width="100">
				<a href="javascript:void(null);" class='new'>new</a>
			</th>
		</tr>
	</thead>
	<tbody>
	<?php foreach($this->items as $model) { ?>
		<tr>
			<td><input type="checkbox" name="chk_<?php echo $model->getPK(); ?>" value="<?php echo $model->getPK(); ?>" /></td>
			<?php foreach($model->values() as $value) { ?>
				<?php
				// Linked Model
				if ($value instanceof AjdeX_Model) { ?>
					<td class="linkedModel" title="<?php echo $value->get($value->getDisplayField()); ?>"><?php echo $value->get($value->getDisplayField()); ?></td>
				<?php
				// Text value
				} else { ?>
					<td title="<?php echo $value; ?>"><?php echo $value; ?></td>
				<?php } ?>			
			<?php } ?>
			<td>
				<a href="javascript:void(null);" class='edit'>edit</a>
				<a href="javascript:void(null);" class='delete'>delete</a>
			</td>
		</tr>
	<?php } ?>
	</tbody>
	</table>

</form>