<?php
/* @var $this Ajde_Template_Parser_Phtml_Helper */
/* @var $field Ajde_Crud_Field_File */
$field = $this->field;

$collectionName = ucfirst($field->getName()) . 'Collection';
$modelName = ucfirst($field->getName()) . 'Model';
$collection = new $collectionName;
/* @var $model Ajde_Model */
$model = new $modelName;
/* @var $collection Ajde_Collection */
$collection->orderBy($model->getDisplayField());

if ($field->hasFilter()) {
	$filter = $field->getFilter();
	$group = new Ajde_Filter_WhereGroup();
	foreach($filter as $rule) {
		$group->addFilter(new Ajde_Filter_Where($model->getDisplayField(), Ajde_Filter::FILTER_EQUALS, $rule, Ajde_Query::OP_OR));
	}
	$collection->addFilter($group);
}

if ($field->hasAdvancedFilter()) {
	$filters = $field->getAdvancedFilter();
	$group = new Ajde_Filter_WhereGroup();
	foreach($filters as $filter) {
		if ($filter instanceof Ajde_Filter_Where) {
			$group->addFilter($filter);
		} else {
			$collection->addFilter($filter);
		}		
	}
	$collection->addFilter($group);
}

$collection->load(); 

if ($field->getValue()) {
	if ($field->getValue() instanceof Ajde_Model) {
		$pk = $field->getValue()->getPK();
	} else {
		$pk = $field->getValue();
	}
} else {
	$pk = null;
}

?>

<select
	<?php echo $field->getHtmlAttributes(); ?>
	<?php if ($field->hasReadonly() && $field->getReadonly() === true) {
		echo ' disabled="disabled" ';	
	} ?>
>
	<?php if (!$field->getIsRequired() === true) { ?>
		<option value=''>(none)</option>
	<?php } ?>
	<?php foreach($collection as $option) { ?>							
		<option value='<?php echo $option; ?>'
			<?php if ($option == $pk) { echo "selected='selected'"; } ?>
			><?php echo $option->get($option->getDisplayField()); ?></option>
	<?php } ?>
</select>