<?php
$field = $this->field;
$options = explode(',', $field->getLength()); ?>

<select
	<?php echo $field->getHtmlAttributes(); ?>
	<?php if ($field->hasReadonly() && $field->getReadonly() === true) {
		echo ' disabled="disabled" ';	
	} ?>
>
	<?php if (!$field->getIsRequired()) { ?>
		<option value=''>(kies <?php echo strtolower($field->getLabel()); ?>)</option>
	<?php } ?>
	<?php foreach($options as $option) { 
		if ($field->hasFilter()) {
			if (!in_array(trim($option, "'"), $field->getFilter())) {
				continue;
			}
		}
		$option = trim($option, "'"); ?>
		<option value='<?php echo $option; ?>'			
			<?php if ($option == $field->getValue()) { echo "selected='selected'"; } ?>
			><?php echo __($option); ?></option>
	<?php } ?>
</select>