<?php
/* @var $this Ajde_Template_Parser_Phtml_Helper */

// Unify the user agent specific css rules
$this->requireCssTop('reset');

// Include jQuery 1.7
$this->requireJsLibrary('jquery', '1.7');

// Some JavaScript i18n
// $this->requireJsFirst('i18n.' . Ajde_Lang::getInstance()->getShortLang());

?>
<!-- Inspired by HTML5 Boilerplate -->
<!doctype html>
<html lang='<?php echo Ajde_Lang::getInstance()->getShortLang(); ?>' id='<?php echo Config::get('ident'); ?>'>
	<head>
		<meta charset='utf-8'>
		<!--[if IE]><![endif]-->
		<title><?php echo _e(Ajde::app()->getDocument()->getTitle()); ?></title>		
		<meta name='description' content='<?php echo _e(Ajde::app()->getDocument()->getDescription()); ?>' />
		<meta name='author' content='<?php echo _e(Config::get('author')); ?>' />
		<?php echo Ajde::app()->getDocument()->getMeta(); ?>
		<base href='http://<?php echo Config::get('lang_root'); ?>' />
		<!-- require JavaScript and cookies -->		
		<noscript>
			<meta http-equiv="refresh" content="0;url=main/nojavascript.html?returnto=<?php echo urlencode((string) Ajde::app()->getRoute()); ?>" />
		</noscript>				
		<script>
			if (navigator.cookieEnabled === false) {
				document.location.href='main/nocookies.html?returnto=<?php echo urlencode((string) Ajde::app()->getRoute()); ?>';
			}
		</script>
		<link rel="shortcut icon" type="image/x-icon" href="favicon.ico" />
		<?php echo $this->getDocument()->getHead('css'); ?>
		<?php echo $this->getDocument()->getHead('less'); ?>
		<script type="text/javascript">
			var _gaq = _gaq || [];
			_gaq.push(['_setAccount', 'UA-XXXXX-X']);
			_gaq.push(['_trackPageview']);
			(function() {
				var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
				ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
				var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
			})();
		</script>
	</head>
	<!--[if lt IE 7 ]> <body class='ie6'> <![endif]-->
	<!--[if IE 7 ]>    <body class='ie7'> <![endif]-->
	<!--[if IE 8 ]>    <body class='ie8'> <![endif]-->
	<!--[if IE 9 ]>    <body class='ie9'> <![endif]-->
	<!--[if (gt IE 9)|!(IE)]><!--> <body> <!--<![endif]-->
		<div id='wrapper'>
			<h1><?php echo Config::get('sitename'); ?></h1>
			<?php echo $this->getDocument()->getBody(); ?>
		</div>
		<?php echo $this->getDocument()->getScripts(); ?>
	</body>
</html>
<!--[<pre>
	<?php $version = Config::get('version'); echo Config::get('ident') . ', v' . $version['number'] . ' (' . $version['name'] . ')'; ?> 
	Cache <?php echo Ajde_Cache::getInstance()->isEnabled() ? 'enabled' : 'disabled' ?> 
	Last modified on <?php echo date("r", Ajde_Cache::getInstance()->getLastModified()); ?> 
</pre><![-->