<?php
/* @var $this Ajde_Template_Parser_Phtml_Helper */
$this->requireCssTop('reset'); 
?>
<!-- Inspired by HTML5 Boilerplate -->
<!doctype html>
<html lang='<?php echo Ajde_Lang::getInstance()->getShortLang(); ?>' id='<?php echo Config::get('ident'); ?>'>
	<head>
		<meta charset='utf-8'>
		<!--[if IE]><![endif]-->
		<title><?php echo Config::get('sitename'); ?></title>
		<base href='http://<?php echo Config::get('site_root'); ?>' />
		<meta name='description' content='' />
		<meta name='author' content='' />
		<!-- require JavaScript and cookies -->		
		<noscript>
		<meta http-equiv="refresh" content="0;url=main/nojavascript.html?returnto=<?php echo urlencode((string) Ajde::app()->getRoute()); ?>" />
		</noscript>				
		<script>
			if (navigator.cookieEnabled === false) {
				document.location.href='main/nocookies.html?returnto=<?php echo urlencode((string) Ajde::app()->getRoute()); ?>';
			}
		</script>
		<?php echo $this->getDocument()->getHead('css'); ?>
	</head>
	<!--[if lt IE 7 ]> <body class='ie6'> <![endif]-->
	<!--[if IE 7 ]>    <body class='ie7'> <![endif]-->
	<!--[if IE 8 ]>    <body class='ie8'> <![endif]-->
	<!--[if IE 9 ]>    <body class='ie9'> <![endif]-->
	<!--[if (gt IE 9)|!(IE)]><!--> <body> <!--<![endif]-->
		<div id='wrapper'>
			<h1><?php echo Config::get('sitename'); ?></h1>
			<?php echo $this->getDocument()->getBody(); ?>
		</div>
		<?php echo $this->getDocument()->getScripts(); ?>
	</body>
</html>
