<?php
/* @var $this Ajde_Template_Parser_Phtml_Helper */
?>

<h2><?php echo __("Welcome to the Ajde Framework"); ?></h2>
<p>
	Yet another PHP 5.0 MVC framework with out-of-the-box HTML / CSS / JS / caching and HTTP optimizations. Your project will be fast and cutting edges right from the start!
</p>
<p>
	<a class='action' href='samples'>
		<?php echo __("View example module"); ?>
	</a>
	<a class='action' href='http://code.google.com/p/ajde/wiki/DocumentationGettingStarted'>
		<?php echo __("Online documentation"); ?>
	</a>	
</p>