<?php
/* @var $this Ajde_Template_Parser_Phtml_Helper */
$this->requireCss('view.mobile', 'html', null, Ajde_Document_Format_Html::RESOURCE_POSITION_LAST, 'media="only screen and (min-width: 320px) and (max-width: 569px)"');
//$this->requireCss('view.mobile', 'html', null, Ajde_Document_Format_Html::RESOURCE_POSITION_LAST, 'media="only screen and (min-device-width: 320px) and (max-device-width: 569px)"');
?>

<h2>Blog</h2>

<p>
	<a href='samples/edit.html?new'>Add post</a> | 
	<a href='samples/edit.html'>Edit posts</a>
</p>

<hr/>

<?php foreach($this->blog as $entry) { ?>
	
	<h3><?php echo $this->escape( $entry->title ); ?></h3>
	<p>
		<em>Written on <?php echo $this->escape( $entry->date ); ?></em> :
	</p>
	<p><?php echo $this->escape( $entry->content ); ?></p>
	
	<hr/>
	
<?php } ?>