<p><?php echo __("welcome"); ?></p>

<h3>Samples</h3>

<ul>
	<li><a href='helloworld.html'>Hello World</a> (Ajde for dummies)</li>
	<li><a href='article.html'>Article</a> (Routing example)</li>
	<li><a href='zend.html'>Zend</a> (Zend Framework example)</li>
	<li><a href='blog.html'>Blog</a> (Working with AjdeX)</li>
	<li><a href='security.html'>Security</a> (Security features)</li>
</ul>

<h3>Ajde Plugins</h3>

<ul>
	<li><a href='user.html'>User</a></li>
	<li><a href='acl.html'>Acl</a></li>
</ul>