<?php
/* @var $this Ajde_Template_Parser_Phtml_Helper */
?>

<h2>Checkout</h2>

<h4>Review your shopping cart</h4>
<?php echo $this->includeModule('shop/cart:widget'); ?>
<p><a class='action small' href="shop/cart:edit">Edit cart</a></p>

<hr/>

<?php if ($this->user) { ?>
	<h4>You are currently logged in as <?php echo _e($this->user->getFullname()); ?></h4>
	<p>We use your account info to pre-fill some details for your order.</p>
	<p><a class='action small' href='shop/cart:switchUser?returnto=shop/checkout'>Switch user</a></p>
<?php } else { ?>
	<h4>You are not currently logged in</h4>
	<p>
		We'll gladly take your order, but if you plan on coming back soon, please
		take some time to register yourself so you won't need to fill out your
		details in the future!
	</p>
	<p>
		<a href='user/register?returnto=shop/checkout' class='action small'>Register for an account</a> When you already have an account here, <a href='user/logon?returnto=shop/checkout'>login now</a>.
	</p>
<?php } ?>
	
<hr/>

<?php if ($this->cart->hasItems()) { ?>
	<p><a class='action' href='shop/transaction:setup'>Proceed with checkout</a></p>
<?php } else { ?>
	<p><a class='action' href='shop'>Do some shopping first</a></p>
<?php } ?>