<?php
/* @var $this Ajde_Template_Parser_Phtml_Helper */ 
?>
<h2>Ajde is a web framework with open standards in mind</h2>
<h3>A framework for designers</h3>
<p>
	A simple to use API and a straightforward templating system for your web
	application. Ajde will automatically include your related JavaScript and
	stylesheets if you follow the naming convention and you can write your
	templates in native PHP or entirely in XML.
</p>
<p>
	Writing your application logic and extending Ajde is easy and extensive
	exception handling is turned on by default. Unless of course you switch from
	the development stage to a live website.
</p>
<h3>A framework for Grade A performance</h3>
<p>
	Ajde aims to be a framework for designers. Employing out-of-the box
	minifiers, resource combining and caching of resources such as JavaScript
	and stylesheet files, and taking care of all the right headers and .htaccess
	settings for you, Ajde lifts the performance of your application to a whole
	next level.
</p>