<?php echo $this->ajaxForm('component/crudCommit', $this->id, 'ACCrudEdit'); ?>
	
	<dl class='crudEdit'>
		<?php foreach($this->fields as $fieldName => $fieldLabel) { ?>
			<dt><?php echo !empty($fieldLabel) ? $fieldLabel : $fieldName; ?></dt>
			<?php
			$value = $this->item->get($fieldName);
			// Linked Model
			if ($value instanceof AjdeExtension_Model) { ?>
				<dd><?php echo $value->get($value->getDisplayField()); ?></dd>
			<?php
			// Text value
			} else { ?>
				<dd>
					<input type="text" name="<?php echo $fieldName; ?>" value="<?php echo $value; ?>" />
				</dd>
			<?php } ?>			
		<?php } ?>
		
		<dt>&nbsp;</dt>
		<dd>
			<button class="save">Save</button>
			<a href="javascript:void(null);" class='cancel'>Cancel</a>
		</dd>
	</dl>
	
</form>