<?php /* @var $this Ajde_Template_Parser_Phtml_Helper */ ?>

<h2>Edit</h2>

<?php
	$fields = array(
		'image' => array(
			'type' => 'file',
			'saveDir' => 'public/images/blog/',
			'extensions' => array('png', 'jpg'),
			'multiple' => false,
			'label' => 'Plaatje',
			'length' => 255,
			'isRequired' => false,
			'default' => '',
			'isAutoIncrement' => false,
			'help' => 'Please select an image, or drag and drop here'
			),
		'published' => array(
			'type' => 'boolean',
			'help' => 'Post is visible or not'
		)
	);
	$list = array(
		'buttons' => array(
			'new' => true,
			'edit' => true,
			'view' => array(
				'text' => 'View article',
				'class' => 'view'
			)
		),
		'show' => array('title', 'date', 'published', 'user', 'type')
	);	
	$options = array(
		'fields'	=> $fields,
		'list'		=> $list
	);
	
	$crud = $this->ACCrudList('blog', $options);
	
	if (Ajde::app()->getRequest()->has('new')) {
		$user = UserModel::getLoggedIn();
		$crud->setOption('fields.user.value', $user->getPK());		
	}
	
	$crud->getCollection()->orderBy('date');
	
	echo $crud->output();
?>