<h2><?php echo __('Logon'); ?></h2>

<p>
	<a href="user/register"><?php echo __('Register'); ?></a>
</p>

<?php echo $this->ACAjaxForm('user/logon', 'loginform'); ?>
	<input type="hidden" name="returnto" id="returnto" value="<?php echo $this->returnto; ?>" />
	<dl>
		<dt><?php echo __(ucfirst($this->user->usernameField)); ?></dt>
		<dd>
			<input type="text" name="<?php echo $this->user->usernameField; ?>" placeholder="" required />
		</dd>
		
		<dt><?php echo __(ucfirst($this->user->passwordField)); ?></dt>
		<dd>
			<input type="password" name="password" placeholder="****" required />
		</dd>
		
		<dd>
			<input type="checkbox" name="rememberme" id="rememberme" />
			<label for="rememberme"><?php echo __('Remember me'); ?></label>
		</dd>
		
		<dd id="loginformStatus"><?php echo $this->clean($this->message); ?></dd>
		
		<dd>
			<input type="submit" value="<?php echo __('Logon'); ?>" />
		</dd>	
	</dl>

</form>