<?php
/* @var $crud AjdeX_Crud */
$crud = $this->crud;
$listOptions = $crud->getOptions('list');
$fieldOptions = $crud->getOptions('fields');
?>

<?php echo $this->ACAjaxForm('_core/crud:commit', $crud->getHash(), 'ACCrudList'); ?>

	<table class='crudList'>
	<thead>
		<tr>
			<th width="25"></th>
			<?php foreach($crud->getFields() as $field) {
				if (isset($listOptions['show']) && (!in_array($field->getName(), $listOptions['show']))) { continue; } ?>
				<th><?php echo $field->getLabel(); ?></th>
			<?php } ?>
			<th width="120">
				<?php if (!(isset($listOptions['new']) && $listOptions['new'] === false)) { ?>
					<a href="javascript:void(null);" class='button new'>new</a>
				<?php } ?>
			</th>
		</tr>
	</thead>
	<tbody>
	<?php foreach($crud->getItems() as $model) {?>
		<tr>
			<td><input type="checkbox" name="chk_<?php echo $model->getPK(); ?>" value="<?php echo $model->getPK(); ?>" /></td>
			<?php foreach($model->values() as $fieldName => $value) {
				if (isset($listOptions['show']) && (!in_array($fieldName, $listOptions['show']))) { continue; } ?>
				<?php
				// Linked Model
				if ($value instanceof AjdeX_Model && $value->hasLoaded()) { ?>
					<td class="linkedModel" title="<?php echo $value->get($value->getDisplayField()); ?>"><?php echo $value->get($value->getDisplayField()); ?></td>
				<?php
				// File
				} elseif ($crud->getField($fieldName) instanceof AjdeX_Crud_Field_File) { 
					$field = $crud->getField($fieldName) ?>
					<td title="<?php echo $this->escape($value); ?>">
						<?php
						$extension = pathinfo($value, PATHINFO_EXTENSION);
						if (in_array(strtolower($extension), array('jpg', 'jpeg', 'png', 'gif'))) {
							echo $this->ACImage(array(
								'filename' => $field->getSaveDir() . $value,
								'width' => 75,
								'height' => 75,
								'crop' => true
							));
							//echo ' ' . $this->escape($value);
						} else {
							echo $this->escape($value);
						}						
						?>
					</td>
				<?php
				// Text value
				} else { ?>
					<td title="<?php echo $this->escape($value); ?>">
						<?php echo substr($this->escape($value), 0, 100); ?>
						<?php if (strlen($this->escape($value)) > 100) { ?>
							...
						<?php } ?>
					</td>
				<?php } ?>			
			<?php } ?>
			<td class='buttons'>
				<a href="javascript:void(null);" class='button edit'>edit</a>
				<?php if (!(isset($listOptions['delete']) && $listOptions['delete'] === false)) { ?>
					<a href="javascript:void(null);" class='button delete'>delete</a>
				<?php } ?>
			</td>
		</tr>
	<?php } ?>
	</tbody>
	</table>

</form>